### ISSUE TITLE
Remove hard coded IP in provision

### ISSUE THREAD

**Issue by jwmatthews** [ansibleplaybookbundle/mediawiki-apb#26]
Let's revisit the below and see if we can remove this hardcoded IP for k8s support.

https://github.com/ansibleplaybookbundle/mediawiki-apb/blame/master/roles/mediawiki/tasks/provision.yml#L13

**Comment by leifmadsen** [comment]
@jwmatthews is this still an issue? The link above doesn't work anymore, but the IP doesn't look static as it is dynamically added to the template now via variable? Close?

```
{% if 'apps.openshift.io' in lookup('k8s', cluster_info='api_groups') %}
          - name: MEDIAWIKI_SITE_SERVER
            value: {{
              lookup(
                'openshift',
                api_version='route.openshift.io/v1',
                kind='Route',
                namespace=namespace,
                resource_name=app_name
              ) | json_query("spec.host")
            }}
{% else %}
          - name: MEDIAWIKI_SITE_SERVER
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
{% endif %}
```

**Comment by jwmatthews** [comment]
@leifmadsen thanks for the note, will close the issue.
